- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -

- name: "Install Nod.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cashe: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
