- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Use n version manager to use Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "Install NPM-distributed command-line tools"
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
    - firebase-tools


- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
