---
- name: "creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "ls"
  command: ls -l .circleci/ansible/roles/deploy/tasks/files
  register: command_output

- debug:
    var: command_output.stdout_lines


- name: "Unarchive backend files"
  unarchive:
    src: .circleci/ansible/roles/deploy/tasks/files/artifact.tar.gz
    dest: ~/backend-app

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu